# Hyperledger Fabric Network - Docker Compose
# This is a basic configuration for development

version: "3.8"

networks:
    voting-network:
        name: voting-network

volumes:
    orderer.voting.com:
    peer0.itb.ac.id:
    peer0.kpu.itb.ac.id:

services:
    # Orderer
    orderer.voting.com:
        container_name: orderer.voting.com
        image: hyperledger/fabric-orderer:2.5
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - ../organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/msp:/var/hyperledger/orderer/msp
            - ../organizations/ordererOrganizations/voting.com/orderers/orderer.voting.com/tls/:/var/hyperledger/orderer/tls
            - orderer.voting.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050
            - 7053:7053
        networks:
            - voting-network

    # ITB Peer
    peer0.itb.ac.id:
        container_name: peer0.itb.ac.id
        image: hyperledger/fabric-peer:2.5
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=voting-network
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peer0.itb.ac.id
            - CORE_PEER_ADDRESS=peer0.itb.ac.id:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.itb.ac.id:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.itb.ac.id:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.itb.ac.id:7051
            - CORE_PEER_LOCALMSPID=ITBMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/itb.ac.id/peers/peer0.itb.ac.id/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/itb.ac.id/peers/peer0.itb.ac.id/tls:/etc/hyperledger/fabric/tls
            - peer0.itb.ac.id:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 7051:7051
        networks:
            - voting-network

    # KPU Peer
    peer0.kpu.itb.ac.id:
        container_name: peer0.kpu.itb.ac.id
        image: hyperledger/fabric-peer:2.5
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=voting-network
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peer0.kpu.itb.ac.id
            - CORE_PEER_ADDRESS=peer0.kpu.itb.ac.id:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.kpu.itb.ac.id:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.kpu.itb.ac.id:9051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.kpu.itb.ac.id:9051
            - CORE_PEER_LOCALMSPID=KPUMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/kpu.itb.ac.id/peers/peer0.kpu.itb.ac.id/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/kpu.itb.ac.id/peers/peer0.kpu.itb.ac.id/tls:/etc/hyperledger/fabric/tls
            - peer0.kpu.itb.ac.id:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 9051:9051
        networks:
            - voting-network

    # CLI for administration
    cli:
        container_name: cli
        image: hyperledger/fabric-tools:2.5
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.itb.ac.id:7051
            - CORE_PEER_LOCALMSPID=ITBMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/itb.ac.id/peers/peer0.itb.ac.id/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/itb.ac.id/peers/peer0.itb.ac.id/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/itb.ac.id/peers/peer0.itb.ac.id/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/itb.ac.id/users/Admin@itb.ac.id/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
            - ../../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
        depends_on:
            - peer0.itb.ac.id
            - peer0.kpu.itb.ac.id
        networks:
            - voting-network
